PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX cb: <http://ontologycentral.com/2010/05/cb/vocab#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT { ?id cb:opening ?id . } 
FROM <http://jobswrap.ontologycentral.com/jobs> 
WHERE { 
	?id cb:name ?name .
	?id cb:office ?office .
    ?office cb:city ?location .
}
