package org.openlids.query;

import java.io.FileWriter;
import java.util.Collection;
import java.util.TreeSet;

import junit.framework.TestCase;

import org.semanticweb.yars.nx.Node;
import org.semanticweb.yars.nx.NodeComparator;
import org.semanticweb.yars.nx.Nodes;

public class LIDSGeoQueryTest extends TestCase {
	
	static String people[] = {
		"http://www.polleres.net/foaf.rdf#me",
		"http://bblfish.net/people/henry/card#me",
		"http://danbri.org/foaf#danbri",
		"http://danny.ayers.name/index.rdf#me",
		"http://harth.org/andreas/foaf#ah",
		"http://richard.cyganiak.de/foaf.rdf#cygri",
		"http://speiserweb.de/sebastian/foaf.rdf#me",
		"http://simia.net/foaf.rdf#denny",
		"http://sw.deri.org/~aidanh/foaf/foaf.rdf#Aidan_Hogan",
		"http://sw.deri.org/~sheila/foaf.rdf#me",
		"http://tomheath.com/id/me",
		"http://www.b-kaempgen.de/foaf.rdf#me",
		"http://www.ivan-herman.net/foaf#me",
		"http://www.lassila.org/ora.rdf#me",
		"http://www.siegfried-handschuh.net/metadata/foaf.rdf#me",
		"http://www.umbrich.net/foaf.rdf#me",
		"http://www.w3.org/People/Berners-Lee/card#i",
		"http://www.w3.org/People/Sandro/data#Sandro_Hawke"

		
/*		"http://aleasoft.hopto.org/~alvaro/weblog/foaf.rdf#me",
		"http://apassant.net/alex",
		"http://apassant.net/foaf.rdf#alex",
		"http://axel.deri.ie/~axepol/foaf.rdf#me",
		"http://b4mad.net/FOAF/goern.rdf#goern",
		"http://bblfish.net/people/henry/card#me",
		"http://ben.adida.net/#me",
		"http://berrueta.net/foaf.rdf#me",
		"http://bigasterisk.com/foaf.rdf#drewp",
		"http://captsolo.net/semweb/foaf-captsolo.rdf#Uldis_Bojars",
		"http://champin.net/foaf.rdf#pa",
		"http://clark.dallas.tx.us/kendall/foaf.rdf#kendall",
		"http://compsoc.nuigalway.ie/~fuzz/foaf.rdf#Fergal_Monaghan",
		"http://criptonita.com/~nacho/foaf.rdf#me",
		"http://crschmidt.net/foaf.rdf#crschmidt",
		"http://danbri.org/foaf#danbri",
		"http://danbri.org/foaf.rdf#danbri",
		"http://danny.ayers.name/index.rdf#me",
		"http://data.boab.info/david/foaf.rdf#me",
		"http://data.semanticweb.org/person/brian-davis",
		"http://data.semanticweb.org/person/daniel-herzig/rdf",
		"http://data.semanticweb.org/person/denny-vrandecic",
		"http://data.semanticweb.org/person/heiner-stuckenschmidt",
		"http://data.semanticweb.org/person/jose-luis-ambite",
		"http://data.semanticweb.org/person/knud-moeller",
		"http://data.semanticweb.org/person/mike-dean",
		"http://data.semanticweb.org/person/simon-scerri",
		"http://davelevy.info/foaf.rdf#me",
		"http://dblp.l3s.de/d2r/page/authors/Christian_Bizer",
		"http://dblp.l3s.de/d2r/resource/authors/Andrew_Philpot",
		"http://dblp.l3s.de/d2r/resource/authors/Susie_Stephens",
		"http://dbpedia.org/resource/Bj",
		"http://dbpedia.org/resource/Dieter_Fensel",
		"http://dbpedia.org/resource/James_Gosling",
		"http://dbpedia.org/resource/James_Martin_%28author%29",
		"http://dbpedia.org/resource/Janne_Corax",
		"http://dbpedia.org/resource/John_Gage",
		"http://dbpedia.org/resource/John_Klensin",
		"http://dbpedia.org/resource/John_Markoff",
		"http://dbpedia.org/resource/John_Seely_Brown",
		"http://dbpedia.org/resource/Knut_J",
		"http://dbpedia.org/resource/Michael_Genesereth",
		"http://dbpedia.org/resource/Roy_Fielding",
		"http://dbpedia.org/resource/Tim_Bray",
		"http://dbpedia.org/resource/Yochai_Benkler",
		"http://dig.csail.mit.edu/2007/wiki/people/JoeLambda#JL",
		"http://dig.csail.mit.edu/2007/wiki/people/RobertHoffmann#RMH",
		"http://dig.csail.mit.edu/People/RRS",
		"http://dig.csail.mit.edu/People/yosi#YES",
		"http://dunken69.myopenid.com/",
		"http://eikeon.com/foaf.rdf#eikeon",
		"http://eikeon.com/foaf.rdf#eikon",
		"http://eneumann.org/foaf/myFOAF.rdf#me",
		"http://eyaloren.org/foaf.rdf#me",
		"http://f-dengler.de/foaf#fd",
		"http://foaf.me/ah1#me",
		"http://foaf.me/dana#me",
		"http://foaf.me/melvincarvalho#me",
		"http://foaf.qdos.com/delicious/people/stefano.bertolo#me",
		"http://foafbuilder.qdos.com/people/asyd.myopenid.com/foaf.rdf#me",
		"http://foafbuilder.qdos.com/people/piaj.blogspot.com/foaf.rdf#me",
		"http://foafbuilder.qdos.com/people/tboudreau.myopenid.com/foaf.rdf#me",
		"http://fooshed.net/foaf.rdf#me",
		"http://g1o.net#me",
		"http://g1o.net/foaf.rdf#me",
		"http://handtwerk.de/foaf.rdf#arne",
		"http://harth.org/andreas/foaf#ah",
		"http://harth.org/andreas/foaf#rene",
		"http://harth.org/andreas/foaf#tim",
		"http://harth.org/andreas/foaf#tony",
		"http://heddley.com/edd/foaf.rdf#edd",
		"http://hege.prestrud.org/foaf#me",
		"http://holgerlausen.net/foaf.rdf#me",
		"http://homepage.ntlworld.com/philnjo/phil/rdf/foaf.rdf#me",
		"http://homepages.cwi.nl/~hildebra/foaf.rdf#node12m2kdnsux1",
		"http://hometown.aol.com/chbussler/foaf/chbussler.foaf#me",
		"http://iandavis.com/id/me",
		"http://iandavis.com/id/paulmiller",
		"http://id.ecs.soton.ac.uk/person/1269",
		"http://id.ecs.soton.ac.uk/person/1650",
		"http://id.ecs.soton.ac.uk/person/21",
		"http://id.ecs.soton.ac.uk/person/2686",
		"http://id.ecs.soton.ac.uk/person/60",
		"http://identi.ca/user/3546",
		"http://inamidst.com/sbp/foaf#Sean",
		"http://infomancer.org/foaf.xml#thosch",
		"http://infomesh.net/2003/people#AaronSwartz",
		"http://infomesh.net/2003/people#AlGilman",
		"http://infomesh.net/2003/people#CMcCN",
		"http://infomesh.net/2003/people#CodyW",
		"http://infomesh.net/2003/people#DamianSteer",
		"http://infomesh.net/2003/people#DanBrickley",
		"http://infomesh.net/2003/people#DannyAyers",
		"http://infomesh.net/2003/people#DaveBeckett",
		"http://infomesh.net/2003/people#DavePawson",
		"http://infomesh.net/2003/people#JimLey",
		"http://infomesh.net/2003/people#LibbyMiller",
		"http://infomesh.net/2003/people#MortenF",
		"http://infomesh.net/2003/people#NickKew",
		"http://infomesh.net/2003/people#NormanWalsh",
		"http://infomesh.net/2003/people#ShahanK",
		"http://infomesh.net/2003/people#StuartYeates",
		"http://infomesh.net/2003/people#TimBL",
		"http://infomesh.net/2003/people#WL",
		"http://infomesh.net/2003/people#WendyChisholm",
		"http://iws.seu.edu.cn/people/gcheng",
		"http://kantenwerk.org/metadata/foaf.rdf#me",
		"http://kasei.us/about/foaf.xrdf#greg",
		"http://kashori.com/JohnBlack/foaf.rdf#jpb",
		"http://keg.cs.tsinghua.edu.cn/persons/tj/jietang.rdf#me",
		"http://kingsley.idehen.name/dataspace/person/kidehen#this",
		"http://kingsley.idehen.net/dataspace/kidehen/socialnetwork/Kingsley%20Uyi%20Idehen%27s%20AddressBook/1000#this",
		"http://kingsley.idehen.net/dataspace/kidehen/socialnetwork/Kingsley%20Uyi%20Idehen%27s%20AddressBook/1001#this",
		"http://kingsley.idehen.net/dataspace/kidehen/socialnetwork/Kingsley%20Uyi%20Idehen%27s%20AddressBook/1002#this",
		"http://kingsley.idehen.net/dataspace/kidehen/socialnetwork/Kingsley%20Uyi%20Idehen%27s%20AddressBook/1003#this",
		"http://kingsley.idehen.net/dataspace/kidehen/socialnetwork/Kingsley%20Uyi%20Idehen%27s%20AddressBook/1004#this",
		"http://kingsley.idehen.net/dataspace/kidehen/socialnetwork/Kingsley%20Uyi%20Idehen%27s%20AddressBook/1005#this",
		"http://kingsley.idehen.net/dataspace/person/kidehen#this",
		"http://kmi.open.ac.uk/people/tom/",
		"http://kwarc.info/clange/foaf/foaf.rdf#me",
		"http://liris.cnrs.fr/olivier.aubert/foaf.rdf#me",
		"http://lsdis.cs.uga.edu/~amit/foaf.rdf#me",
		"http://m3pe.org/~eyal/foaf.rdf#me",
		"http://metacognition.info/profile/webwho.xrdf#chime",
		"http://mmt.me.uk/foaf.rdf#mischa",
		"http://my.opera.com/AVL/xml/foaf#me", */
	//	"http://my.opera.com/Aleksander/xml/foaf#me",
//		"http://my.opera.com/AquariusAnita/xml/foaf#me",
//		"http://my.opera.com/Ashina/xml/foaf#me",
//		"http://my.opera.com/B%C3%BAzavir%C3%A1g46/xml/foaf#me",
//		"http://my.opera.com/Benjamin%20Joffe/xml/foaf#me",
//		"http://my.opera.com/BrunIF/xml/foaf#me",
//		"http://my.opera.com/Cesarsan/xml/foaf#me",
//		"http://my.opera.com/ChiaraInThePond/xml/foaf#me",
//		"http://my.opera.com/Cyro/xml/foaf#me",
//		"http://my.opera.com/DanielHendrycks/xml/foaf#me",
//		"http://my.opera.com/DanielVartanov/xml/foaf#me",
//		"http://my.opera.com/DannyAyers/xml/foaf#me",
//		"http://my.opera.com/DeadFire/xml/foaf#me",
//		"http://my.opera.com/Defvyb/xml/foaf#me",
//		"http://my.opera.com/Demre26/xml/foaf#me",
//		"http://my.opera.com/Dizzzing/xml/foaf#me",
//		"http://my.opera.com/EivindFS/xml/foaf#me",
//		"http://my.opera.com/FataL/xml/foaf#me",
//		"http://my.opera.com/Helmers/xml/foaf#me",
//		"http://my.opera.com/IceArdor/xml/foaf#me",
	//	"http://my.opera.com/IlyaShpankov/xml/foaf#me",
//		"http://my.opera.com/InfernalHacker/xml/foaf#me",
//		"http://my.opera.com/JavaWoman/xml/foaf#me",
//		"http://my.opera.com/JibberJim/xml/foaf#me",
//		"http://my.opera.com/Joen/xml/foaf#me",
//		"http://my.opera.com/Jon/xml/foaf#me",
//		"http://my.opera.com/Julianaseven/xml/foaf#me",
//		"http://my.opera.com/KingZo/xml/foaf#me",
//		"http://my.opera.com/Lawmune/xml/foaf#me",
//		"http://my.opera.com/LilleHerbern/xml/foaf#me",
//		"http://my.opera.com/Lisien/xml/foaf#me",
//		"http://my.opera.com/MacDev_ed/xml/foaf#me",
//		"http://my.opera.com/ManneS/xml/foaf#me",
//		"http://my.opera.com/Mimi5/xml/foaf#me",
//		"http://my.opera.com/MissPlaced/xml/foaf#me",
//		"http://my.opera.com/OperaSinger/xml/foaf#me",
//		"http://my.opera.com/Pecorra/xml/foaf#me",
//		"http://my.opera.com/Ramunas/xml/foaf#me",
//		"http://my.opera.com/ResearchWizard/xml/foaf#me",
//		"http://my.opera.com/RobbieGee/xml/foaf#me",
//		"http://my.opera.com/Scenariogirl/xml/foaf#me",
//		"http://my.opera.com/SerbianFighter/xml/foaf#me",
//		"http://my.opera.com/SergeWood/xml/foaf#me",
//		"http://my.opera.com/Sharebear/xml/foaf#me",
//		"http://my.opera.com/Snorre/xml/foaf#me",
//		"http://my.opera.com/Stein/xml/foaf#me",
//		"http://my.opera.com/SupernevZA/xml/foaf#me",
//		"http://my.opera.com/TR3NT/xml/foaf#me",
//		"http://my.opera.com/TheAtilla/xml/foaf#me",
//		"http://my.opera.com/Think/xml/foaf#me",
//		"http://my.opera.com/Thruth/xml/foaf#me",
//		"http://my.opera.com/TriMN/xml/foaf#me",
//		"http://my.opera.com/VovkaUA/xml/foaf#me",
//		"http://my.opera.com/White%20Lynx/xml/foaf#me",
//		"http://my.opera.com/Xaer/xml/foaf#me",
//		"http://my.opera.com/Yokanan/xml/foaf#me",
//		"http://my.opera.com/ZaraL/xml/foaf#me",
//		"http://my.opera.com/alexdavydova/xml/foaf#me",
//		"http://my.opera.com/alexeik/xml/foaf#me",
//		"http://my.opera.com/andersm/xml/foaf#me",
//		"http://my.opera.com/andreasbovens/xml/foaf#me",
//		"http://my.opera.com/annaraj/xml/foaf#me",
//		"http://my.opera.com/anne/xml/foaf#me",
//		"http://my.opera.com/away/xml/foaf#me",
//		"http://my.opera.com/azeroo/xml/foaf#me",
//		"http://my.opera.com/bektour/xml/foaf#me",
//		"http://my.opera.com/brianj/xml/foaf#me",
//		"http://my.opera.com/brightestvega/xml/foaf#me",
//		"http://my.opera.com/calande/xml/foaf#me",
//		"http://my.opera.com/carolineb/xml/foaf#me",
//		"http://my.opera.com/castaway/xml/foaf#me",
//		"http://my.opera.com/chaals/xml/foaf#me",
//		"http://my.opera.com/cheshrkat/xml/foaf#me",
//		"http://my.opera.com/chris_uribe/xml/foaf#me",
//		"http://my.opera.com/citoyen/xml/foaf#me",
//		"http://my.opera.com/csant/xml/foaf#me",
//		"http://my.opera.com/danbri/xml/foaf#me",
//		"http://my.opera.com/danielcs/xml/foaf#me",
//		"http://my.opera.com/danigoldman/xml/foaf#me",
//		"http://my.opera.com/danya5672/xml/foaf#me",
//		"http://my.opera.com/dramatic/xml/foaf#me",
//		"http://my.opera.com/dstorey/xml/foaf#me",
//		"http://my.opera.com/e-jit/xml/foaf#me",
//		"http://my.opera.com/eiriks/xml/foaf#me",
//		"http://my.opera.com/eskils/xml/foaf#me",
//		"http://my.opera.com/evamen/xml/foaf#me",
//		"http://my.opera.com/extremkz/xml/foaf#me",
//		"http://my.opera.com/fearphage/xml/foaf#me",
//		"http://my.opera.com/feldgendler/xml/foaf#me",
		//"http://my.opera.com/fluffybunny/xml/foaf#me",
//		"http://my.opera.com/fmpalinkas/xml/foaf#me",
//		"http://my.opera.com/foolip/xml/foaf#me",
//		"http://my.opera.com/fred/xml/foaf#me",
//		"http://my.opera.com/g00dspeed/xml/foaf#me",
//		"http://my.opera.com/gautam_chandna/xml/foaf#me",
//		"http://my.opera.com/gefix/xml/foaf#me",
//		"http://my.opera.com/georgien/xml/foaf#me",
//		"http://my.opera.com/glish/xml/foaf#me",
//		"http://my.opera.com/gnapse/xml/foaf#me",
//		"http://my.opera.com/gorme/xml/foaf#me",
//		"http://my.opera.com/gsenarcl/xml/foaf#me",
//		"http://my.opera.com/haavard/xml/foaf#me",
//		"http://my.opera.com/hbjarno/xml/foaf#me",
//		"http://my.opera.com/hefa/xml/foaf#me",
//		"http://my.opera.com/howcome/xml/foaf#me",
//		"http://my.opera.com/huibk/xml/foaf#me",
//		"http://my.opera.com/inaomurchu/xml/foaf#me",
//		"http://my.opera.com/inkel/xml/foaf#me",
//		"http://my.opera.com/ismailp/xml/foaf#me",
//		"http://my.opera.com/j_stand/xml/foaf#me",
//		"http://my.opera.com/jax/xml/foaf#me",
//		"http://my.opera.com/jod999/xml/foaf#me",
//		"http://my.opera.com/johnfoliot/xml/foaf#me",
//		"http://my.opera.com/jorunnix/xml/foaf#me",
//		"http://my.opera.com/jsmanrique/xml/foaf#me",
//		"http://my.opera.com/keiki/xml/foaf#me",
//		"http://my.opera.com/ketoyo/xml/foaf#me",
//		"http://my.opera.com/kg1.foresights/xml/foaf#me",
//		"http://my.opera.com/kjetilk/xml/foaf#me",
//		"http://my.opera.com/kncarlsen/xml/foaf#me",
//		"http://my.opera.com/koalie/xml/foaf#me",
//		"http://my.opera.com/kumenova/xml/foaf#me",
//		"http://my.opera.com/lachralle/xml/foaf#me",
//		"http://my.opera.com/larskl/xml/foaf#me",
//		"http://my.opera.com/liddyn/xml/foaf#me",
//		"http://my.opera.com/lmaspons/xml/foaf#me",
//		"http://my.opera.com/lynnr/xml/foaf#me",
//		"http://my.opera.com/magnez/xml/foaf#me",
//		"http://my.opera.com/malware/xml/foaf#me",
//		"http://my.opera.com/marianh/xml/foaf#me",
//		"http://my.opera.com/mcx/xml/foaf#me",
//		"http://my.opera.com/melnichuck/xml/foaf#me",
//		"http://my.opera.com/merlo/xml/foaf#me",
//		"http://my.opera.com/minch/xml/foaf#me",
//		"http://my.opera.com/mitchman2/xml/foaf#me",
//		"http://my.opera.com/mollydotcom/xml/foaf#me",
//		"http://my.opera.com/msmiffy/xml/foaf#me",
//		"http://my.opera.com/mursya/xml/foaf#me",
//		"http://my.opera.com/myfrenchopera/xml/foaf#me",
//		"http://my.opera.com/nafmo/xml/foaf#me",
//		"http://my.opera.com/navjotpawera/xml/foaf#me",
//		"http://my.opera.com/nicomen/xml/foaf#me",
//		"http://my.opera.com/oedipus/xml/foaf#me",
//		"http://my.opera.com/olegt/xml/foaf#me",
//		"http://my.opera.com/olli/xml/foaf#me",
//		"http://my.opera.com/onlyputri/xml/foaf#me",
//		"http://my.opera.com/opera-shacho/xml/foaf#me",
//		"http://my.opera.com/opera_jp/xml/foaf#me",
//		"http://my.opera.com/over/xml/foaf#me",
//		"http://my.opera.com/oyvindst/xml/foaf#me",
//		"http://my.opera.com/p01/xml/foaf#me",
//		"http://my.opera.com/pROCKrammer/xml/foaf#me",
//		"http://my.opera.com/patrickhlauke/xml/foaf#me",
//		"http://my.opera.com/pavel.studeny/xml/foaf#me",
//		"http://my.opera.com/pepelsbey/xml/foaf#me",
//		"http://my.opera.com/plg/xml/foaf#me",
//		"http://my.opera.com/ptckian/xml/foaf#me",
//		"http://my.opera.com/pvojnisek/xml/foaf#me",
//		"http://my.opera.com/rafaeltech/xml/foaf#me",
//		"http://my.opera.com/revolverfactory/xml/foaf#me",
//		"http://my.opera.com/robin-berjon/xml/foaf#me",
//		"http://my.opera.com/robocop48id/xml/foaf#me",
//		"http://my.opera.com/rosiemacq/xml/foaf#me",
//		"http://my.opera.com/runeh/xml/foaf#me",
//		"http://my.opera.com/ryonaitis/xml/foaf#me",
//		"http://my.opera.com/saito/xml/foaf#me",
//		"http://my.opera.com/shwetankdixit/xml/foaf#me",
//		"http://my.opera.com/spz/xml/foaf#me",
//		"http://my.opera.com/staceyc/xml/foaf#me",
//		"http://my.opera.com/stephan/xml/foaf#me",
//		"http://my.opera.com/sverre/xml/foaf#me",
//		"http://my.opera.com/theoperalink/xml/foaf#me",
//		"http://my.opera.com/timbl/xml/foaf#me",
//		"http://my.opera.com/timjoh/xml/foaf#me",
//		"http://my.opera.com/toman/xml/foaf#me",
//		"http://my.opera.com/tomheath/xml/foaf#me",
//		"http://my.opera.com/velmu/xml/foaf#me",
//		"http://my.opera.com/vetler/xml/foaf#me",
//		"http://my.opera.com/virtuelvis/xml/foaf#me",
//		"http://my.opera.com/wapxana/xml/foaf#me",
//		"http://my.opera.com/yennyotero/xml/foaf#me",
//		"http://my.opera.com/yitzhaq/xml/foaf#me",
//		"http://my.opera.com/yngve/xml/foaf#me",
//		"http://my.opera.com/zarkoh/xml/foaf#me",
//		"http://my.opera.com/zcorpan/xml/foaf#me",
//		"http://my.opera.com/zoso/xml/foaf#me",
//		"http://myopenlink.net/dataspace/person/kidehen#this",
//		"http://myopenlink.net/dataspace/person/kidehen%23this",
//		"http://nets.ii.uam.es/~rlara/foaf.rdf#me",
//		"http://norman.walsh.name/knows/who#norman-walsh",
//		"http://ns.inria.fr/fabien.gandon/",
//		"http://nunolopes.org/foaf.rdf#me",
//		"http://ontoworld.org/wiki/Special:URIResolver/Andreas_Harth",
//		"http://ontoworld.org/wiki/Special:URIResolver/Juanzi_Li",
//		"http://ontoworld.org/wiki/Special:URIResolver/Vanessa_Lopez",
//		"http://ontoworld.org/wiki/Special:URIResolver/Yuangui_Lei",
//		"http://ontoworld.org/wiki/Special:URIResolver/Zhisheng_Huang",
//		"http://page.mi.fu-berlin.de/mochol/foaf.rdf#me",
//		"http://page.mi.fu-berlin.de/~nixon/foaf.rdf#nixon",
//		"http://people.apache.org/~oshani/foaf.rdf#me",
//		"http://people.csail.mit.edu/crowell/foaf.rdf#crowell",
//		"http://people.csail.mit.edu/crowell/semanticwebiswesome.rdf#semanticwebisawesome",
//		"http://people.csail.mit.edu/lkagal/foaf#me",
//		"http://people.csail.mit.edu/psz/foaf.rdf#me",
//		"http://people.csail.mit.edu/ryanlee/about#ryanlee",
//		"http://people.w3.org/simon/foaf#i",
//		"http://petra.euitio.uniovi.es/~i1637566/foaf.rdf#me",
//		"http://plugin.org.uk/swh.xrdf#me",
//		"http://polleres.net/foaf.rdf#me",
//		"http://presbrey.mit.edu/foaf#presbrey",
//		"http://purl.oclc.org/NET/gearon/people/PaulGearon/foaf.rdf#me",
//		"http://purl.org/captsolo/semweb/foaf-captsolo.rdf#Uldis_Bojars",
//		"http://purl.org/net/clange",
//		"http://qdos.com/people/tom.xrdf#me",
//		"http://renaud.delbru.fr/rdf/foaf#me",
//		"http://richard.cyganiak.de/foaf.rdf#cygri",
//		"http://richard.cyganiak.de/foaf.rdf",
//		"http://rit.mellon.org/Members/ihf/foaf.rdf#me",
//		"http://sebastian.dietzold.de/terms/me",
//		"http://sebastian.tramp.name",
//		"http://semanticweb.org/id/Antoine_Zimmermann",
//		"http://semanticweb.org/id/Jerome_Euzenat",
//		"http://semanticweb.org/id/Siegfried_Handschuh",
//		"http://semanticweb.org/id/Stefan_Decker",
//		"http://semedia.deit.univpm.it/people/christian/foaf.rdf#me",
//		"http://simia.net/foaf.rdf#denny",
//		"http://speiserweb.de/sebastian/foaf.rdf#me",
//		"http://stefanbischof.at/foaf.rdf#me",
//		"http://sw-app.org/mic.xhtml#i",
//		"http://sw.deri.org/~aidanh/foaf/foaf.rdf#Aidan_Hogan",
//		"http://sw.deri.org/~bnsapkota/foaf.rdf#me",
//		"http://sw.deri.org/~haller/foaf.rdf#ah",
//		"http://sw.deri.org/~knud/",
//		"http://sw.deri.org/~knud",
//		"http://sw.deri.org/~scorlosquet/foaf.rdf#me",
//		"http://sw.deri.org/~scorlosquet/foaf.rdf#rene",
//		"http://sw.deri.org/~sheila/foaf.rdf#me",
//		"http://swiss.csail.mit.edu/users/cph/foaf.rdf#cph",
//		"http://swordfish.rdfweb.org/people/libby/rdfweb/webwho.xrdf#me",
//		"http://teole.jfouffa.org/People/Teole/card.rdf#me",
//		"http://thefigtrees.net/lee/ldf-card#LDF",
//		"http://tobyinkster.co.uk/#i",
//		"http://tobyinster.co.uk/i",
//		"http://tomheath.com/id/me",
//		"http://tommorris.org/foaf#me",
//		"http://torrez.us/who#elias",
//		"http://trust.mindswap.org/cgi-bin/FilmTrust/foaf.cgi?user=Anerme_wisecrack#Anerme_wisecrack",
//		"http://trust.mindswap.org/cgi-bin/FilmTrust/foaf.cgi?user=RunWithScissors#RunWithScissors",
//		"http://trust.mindswap.org/cgi-bin/FilmTrust/foaf.cgi?user=aaronsw#aaronsw",
//		"http://trust.mindswap.org/cgi-bin/FilmTrust/foaf.cgi?user=bparsia#bparsia",
//		"http://trust.mindswap.org/cgi-bin/FilmTrust/foaf.cgi?user=djweitzner#djweitzner",
//		"http://trust.mindswap.org/cgi-bin/FilmTrust/foaf.cgi?user=erim#erim",
//		"http://trust.mindswap.org/cgi-bin/FilmTrust/foaf.cgi?user=evren#evren",
//		"http://trust.mindswap.org/cgi-bin/FilmTrust/foaf.cgi?user=finin#finin",
//		"http://trust.mindswap.org/cgi-bin/FilmTrust/foaf.cgi?user=golbeck#golbeck",
//		"http://trust.mindswap.org/cgi-bin/FilmTrust/foaf.cgi?user=jenmarie#jenmarie",
//		"http://trust.mindswap.org/cgi-bin/FilmTrust/foaf.cgi?user=jtyler#jtyler",
//		"http://trust.mindswap.org/cgi-bin/FilmTrust/foaf.cgi?user=kendall#kendall",
//		"http://trust.mindswap.org/cgi-bin/FilmTrust/foaf.cgi?user=ronwalf#ronwalf",
//		"http://trust.mindswap.org/cgi-bin/FilmTrust/foaf.cgi?user=sbp#sbp",
//		"http://trust.mindswap.org/cgi-bin/FilmTrust/foaf.cgi?user=vard#vard",
//		"http://tuukka.iki.fi/tuukka#person",
//		"http://users.ecs.soton.ac.uk/mc/mcfoaf.rdf#me",
//		"http://userver.ftw.at/~zhdanova/foaf.rdf#me",
//		"http://wiki.sembase.at/index.php/_Martin_Hepp",
		/* "http://www-cdr.stanford.edu/~petrie/foaf.rdf#me",
		"http://www-di.inf.puc-rio.br/schwabe//foaf-schwabe.rdf#dschwabe",
		"http://www-di.inf.puc-rio.br/schwabe/foaf-schwabe.rdf#me",
		"http://www.aaronsw.com/about.xrdf#aaronsw",
		"http://www.advogato.org/person/connolly/foaf.rdf#me",
		"http://www.aifb.kit.edu/web/Basil_Ell",
		"http://www.aifb.uni-karlsruhe.de/Personen/viewPersonOWL/id2076instance",
		"http://www.aifb.uni-karlsruhe.de/Personen/viewPersonOWL/id2084instance",
		"http://www.aifb.uni-karlsruhe.de/WBS/awa/foaf.rdf#andreas",
		"http://www.anjeve.de/foaf.rdf#AnjaJentzsch",
		"http://www.asturlinux.org/~jsmanrique/foaf.rdf#me",
		"http://www.b-kaempgen.de/foaf.rdf#me",
		"http://www.beaufour.dk/#beaufour",
		"http://www.bizer.de#chris",
		"http://www.blogweb.co.kr/haklae.rdf#me",
		"http://www.cambridgesemantics.com/people/lee", */
		//"http://www.cornelius-rabsch.de/foaf.rdf#me",
//		"http://www.cs.rpi.edu/~hendler/foaf.rdf#jhendler",
//		"http://www.cs.umd.edu/~hendler/2003/foaf.rdf#jhendler",
//		"http://www.cs.vu.nl/~frankh/foaf.rdf#A10",
//		"http://www.cs.vu.nl/~guus/foaf.rdf#me",
//		"http://www.cs.vu.nl/~laroyo/foaf.rdf#me",
//		"http://www.cs.vu.nl/~pmika/foaf.rdf#me",
//		"http://www.dag.kjernsmo.net/foaf#me",
//		"http://www.dajobe.org/foaf.rdf#i",
//		"http://www.dayures.net/foaf.rdf#tejo",
//		"http://www.dcs.shef.ac.uk/~mrowe/foaf.rdf#me",
//		"http://www.debruijn.net/#me",
//		"http://www.deri.ie/about/team/member/Aidan_Finn#me",
//		"http://www.deri.ie/about/team/member/Aidan_Hogan#me",
//		"http://www.deri.ie/about/team/member/Andreas_Harth#me",
//		"http://www.deri.ie/about/team/member/Antoine_Zimmermann#me",
//		"http://www.deri.ie/about/team/member/Armin_Haller#me",
//		"http://www.deri.ie/about/team/member/Behrang_Qasemizadeh#me",
//		"http://www.deri.ie/about/team/member/Bill_McDaniel#me",
//		"http://www.deri.ie/about/team/member/Darragh_Grealish#me",
//		"http://www.deri.ie/about/team/member/Doug_Foxvog#me",
//		"http://www.deri.ie/about/team/member/Eyal_Oren#me",
//		"http://www.deri.ie/about/team/member/Ina_O%27Murchu#me",
//		"http://www.deri.ie/about/team/member/John_Breslin#me",
//		"http://www.deri.ie/about/team/member/Karl_Aberer#me",
//		"http://www.deri.ie/about/team/member/Knud_M",
//		"http://www.deri.ie/about/team/member/Laurentiu_Vasiliu#me",
//		"http://www.deri.ie/about/team/member/Stefan_Decker#me",
//		"http://www.dfki.uni-kl.de/~grimnes/foaf.rdf#ggrimnes",
//		"http://www.di.uniovi.es/~labra/labraFoaf.rdf#me",
//		"http://www.discoveringidentity.com/foaf.rdf#me",
//		"http://www.esis.no/data/robert.engels/foaf.rdf#me",
//		"http://www.fosi.org/people/philarcher/foaf.rdf#me",
//		"http://www.fundacionctic.org/web/contenidos/es/personal/personal_0007.html#polo",
//		"http://www.gassert.ch/foaf/hannes.rdf#hannesgassert",
//		"http://www.georgikobilarov.com/foaf.rdf#me",
//		"http://www.holgerlausen.net/foaf.rdf#me",
//		"http://www.ibiblio.org/hhalpin#",
//		"http://www.ibiblio.org/hhalpin/foaf.rdf#me",
//		"http://www.ifi.unizh.ch/ddis/fileadmin/user_upload/kiefer/foaf.rdf#christophkiefer",
//		"http://www.ifi.uzh.ch/ddis/fileadmin/user_upload/avi/#me",
//		"http://www.ifomis.org/people/holger/foaf.rdf#holger",
//		"http://www.ihmc.us/users/phayes/PatHayes",
//		"http://www.informatik.uni-leipzig.de/~auer/foaf.rdf#me",
//		"http://www.isi.edu/~gil/foaf.rdf#me",
//		"http://www.itee.uq.edu.au/~dwood/dave.rdf#me",
//		"http://www.ivan-herman.net/foaf#me",
//		"http://www.ivan-herman.net/foaf.rdf#me",
//		"http://www.ivan-herman.net/foafExtras.rdf#AlanR",
//		"http://www.ivan-herman.net/foafExtras.rdf#Amy",
//		"http://www.ivan-herman.net/foafExtras.rdf#Art",
//		"http://www.ivan-herman.net/foafExtras.rdf#Brian",
//		"http://www.ivan-herman.net/foafExtras.rdf#BrianK",
//		"http://www.ivan-herman.net/foafExtras.rdf#BruceD",
//		"http://www.ivan-herman.net/foafExtras.rdf#CSMA",
//		"http://www.ivan-herman.net/foafExtras.rdf#ChrisW",
//		"http://www.ivan-herman.net/foafExtras.rdf#Coralie",
//		"http://www.ivan-herman.net/foafExtras.rdf#Dino",
//		"http://www.ivan-herman.net/foafExtras.rdf#Dom",
//		"http://www.ivan-herman.net/foafExtras.rdf#EricM",
//		"http://www.ivan-herman.net/foafExtras.rdf#EricP",
//		"http://www.ivan-herman.net/foafExtras.rdf#HugoH",
//		"http://www.ivan-herman.net/foafExtras.rdf#Ian",
//		"http://www.ivan-herman.net/foafExtras.rdf#IanH",
//		"http://www.ivan-herman.net/foafExtras.rdf#Karen",
//		"http://www.ivan-herman.net/foafExtras.rdf#Karl",
//		"http://www.ivan-herman.net/foafExtras.rdf#Liam",
//		"http://www.ivan-herman.net/foafExtras.rdf#Liddy",
//		"http://www.ivan-herman.net/foafExtras.rdf#MaxF",
//		"http://www.ivan-herman.net/foafExtras.rdf#Melli",
//		"http://www.ivan-herman.net/foafExtras.rdf#PhilA",
//		"http://www.ivan-herman.net/foafExtras.rdf#Ralph",
//		"http://www.ivan-herman.net/foafExtras.rdf#Richard",
//		"http://www.ivan-herman.net/foafExtras.rdf#Sandro",
//		"http://www.ivan-herman.net/foafExtras.rdf#Simon",
//		"http://www.ivan-herman.net/foafExtras.rdf#SimonKaplan",
//		"http://www.ivan-herman.net/foafExtras.rdf#Steven",
//		"http://www.ivan-herman.net/foafExtras.rdf#Susie",
//		"http://www.ivan-herman.net/foafExtras.rdf#TomB",
//		"http://www.ivan-herman.net/foafExtras.rdf#Tonya",
//		"http://www.ivan-herman.net/foafExtras.rdf#YvesL",
//		"http://www.ivan-herman.net/foafExtras.rdf#bernardo",
//		"http://www.ivan-herman.net/foafExtras.rdf#bijan",
//		"http://www.ivan-herman.net/foafExtras.rdf#carsten",
//		"http://www.ivan-herman.net/foafExtras.rdf#dsr",
//		"http://www.ivan-herman.net/foafExtras.rdf#ezzat",
//		"http://www.ivan-herman.net/foafExtras.rdf#hausenblas",
//		"http://www.ivan-herman.net/foafExtras.rdf#huajun",
//		"http://www.ivan-herman.net/foafExtras.rdf#jjc",
//		"http://www.ivan-herman.net/foafExtras.rdf#labra",
//		"http://www.ivan-herman.net/foafExtras.rdf#manu",
//		"http://www.ivan-herman.net/foafExtras.rdf#markb",
//		"http://www.ivan-herman.net/foafExtras.rdf#motik",
//		"http://www.ivan-herman.net/foafExtras.rdf#mschneider",
//		"http://www.ivan-herman.net/foafExtras.rdf#schwabe",
//		"http://www.ivan-herman.net/foafExtras.rdf#uli",
//		"http://www.ivan-herman.net/foafExtras.rdf#vojnisek",
//		"http://www.ivan-herman.net/foafExtras.rdf#zhe",
//		"http://www.ivan-herman.net/me",
//		"http://www.ivanminguez.net/foaf.rdf#me",
//		"http://www.johnbreslin.com/foaf/foaf.rdf#cloud",
//		"http://www.johnbreslin.com/foaf/foaf.rdf#me",
//		"http://www.kagueto.net/files/foaf.rdf#me",
//		"http://www.kjetil.kjernsmo.net/foaf#me",
//		"http://www.kjetil.kjernsmo.net/foaf.rdf#me",
//		"http://www.koalazoo.es/foaf.rdf#me",
//		"http://www.kr.tuwien.ac.at/staff/former_staff/roman/foaf.rdf#me",
//		"http://www.lassila.org/ora.rdf#me",
//		"http://www.leobard.net/rdf/foaf.xml#me",
//		"http://www.lri.fr/~pietriga/foaf.rdf#EP",
//		"http://www.mindswap.org/2004/owl/mindswappers#Aaron.Mannes",
//		"http://www.mindswap.org/2004/owl/mindswappers#Aditya.Kalyanpur",
//		"http://www.mindswap.org/2004/owl/mindswappers#Amy.Alford",
//		"http://www.mindswap.org/2004/owl/mindswappers#Anant.Kaushiva",
//		"http://www.mindswap.org/2004/owl/mindswappers#Andrew.Schain",
//		"http://www.mindswap.org/2004/owl/mindswappers#Bernardo.Cuenca",
//		"http://www.mindswap.org/2004/owl/mindswappers#Bijan.Parsia",
//		"http://www.mindswap.org/2004/owl/mindswappers#Bin.Zhao",
//		"http://www.mindswap.org/2004/owl/mindswappers#Chris.Shenton",
//		"http://www.mindswap.org/2004/owl/mindswappers#Chris.Testa",
//		"http://www.mindswap.org/2004/owl/mindswappers#Christian.Halaschek",
//		"http://www.mindswap.org/2004/owl/mindswappers#Daniel.Hewlett",
//		"http://www.mindswap.org/2004/owl/mindswappers#Daniel.Krech",
//		"http://www.mindswap.org/2004/owl/mindswappers#Dave.Wang",
//		"http://www.mindswap.org/2004/owl/mindswappers#David_Wood",
//		"http://www.mindswap.org/2004/owl/mindswappers#Debbie.Heisler",
//		"http://www.mindswap.org/2004/owl/mindswappers#Edna.Ruckhaus",
//		"http://www.mindswap.org/2004/owl/mindswappers#Evren.Sirin",
//		"http://www.mindswap.org/2004/owl/mindswappers#Femke.Reitsma",
//		"http://www.mindswap.org/2004/owl/mindswappers#Grecia.Lapizco-Encinas",
//		"http://www.mindswap.org/2004/owl/mindswappers#Hamid_Haidarian-Shahri",
//		"http://www.mindswap.org/2004/owl/mindswappers#Hidenari.Kiyomitsu",
//		"http://www.mindswap.org/2004/owl/mindswappers#Jay.Banerjee",
//		"http://www.mindswap.org/2004/owl/mindswappers#Jennifer.Golbeck",
//		"http://www.mindswap.org/2004/owl/mindswappers#Jim.Hendler",
//		"http://www.mindswap.org/2004/owl/mindswappers#Jordan.Katz",
//		"http://www.mindswap.org/2004/owl/mindswappers#Kaoru.Hiramatsu",
//		"http://www.mindswap.org/2004/owl/mindswappers#Katy.Newton",
//		"http://www.mindswap.org/2004/owl/mindswappers#Kendall.Clark",
//		"http://www.mindswap.org/2004/owl/mindswappers#Matt.Westhoff",
//		"http://www.mindswap.org/2004/owl/mindswappers#Meem.Mahmud",
//		"http://www.mindswap.org/2004/owl/mindswappers#Mike.Grove",
//		"http://www.mindswap.org/2004/owl/mindswappers#Nada.Hashmi",
//		"http://www.mindswap.org/2004/owl/mindswappers#Naiwen.Lin",
//		"http://www.mindswap.org/2004/owl/mindswappers#Ron.Alford",
//		"http://www.mindswap.org/2004/owl/mindswappers#Ron.Reck",
//		"http://www.mindswap.org/2004/owl/mindswappers#Ross.Baker",
//		"http://www.mindswap.org/2004/owl/mindswappers#Ugur_Kuter",
//		"http://www.mindswap.org/2004/owl/mindswappers#Vladimir_Kolovski",
//		"http://www.mindswap.org/2004/owl/mindswappers#Yvonne.Shashoua",
//		"http://www.okkam.org/entity/200706301185791252056",
//		"http://www.openlinksw.com/dataspace/kidehen@openlinksw.com/about.rdf#this",
//		"http://www.openlinksw.com/dataspace/oerling#person",
//		"http://www.openlinksw.com/dataspace/person/oerling#this",
//		"http://www.polleres.net/foaf.rdf#me",
//		"http://www.postsubmeta.net/foaf.rdf#TK",
//		"http://www.real-programmer.com/foaf/chbussler.foaf#me",
//		"http://www.semantic-web.at/people/blumauer/card#me",
//		"http://www.siegfried-handschuh.net/metadata/foaf.rdf#me",
//		"http://www.soumitrabhattacharya.com/foaf.rdf#me",
//		"http://www.stud.uni-karlsruhe.de/~uhbnq/martin/foaf.rdf#mz",
//		"http://www.synne.kjernsmo.net/foaf#me",
//		"http://www.talkdigger.com/foaf/fgiasson",
//		"http://www.topquadrant.com/people/dallemang/foaf.rdf#me",
//		"http://www.tudorgroza.org/res/foaf.rdf#me",
//		"http://www.umbrich.net/foaf.rdf#me",
//		"http://www.uni-koblenz.de/~sschenk/foaf.rdf#me",
//		"http://www.w3.org/People/Berners-Lee/card#amy",
//		"http://www.w3.org/People/Berners-Lee/card#cm",
//		"http://www.w3.org/People/Berners-Lee/card#dj",
//		"http://www.w3.org/People/Berners-Lee/card#edd",
//		"http://www.w3.org/People/Berners-Lee/card#i",
//		"http://www.w3.org/People/Bratt/stevenrbratt.rdf#me",
//		"http://www.w3.org/People/Connolly/#me",
//		"http://www.w3.org/People/EM/contact#me",
//		"http://www.w3.org/People/Jacobs/contact.rdf#IanJacobs",
//		"http://www.w3.org/People/Josema/#josema",
//		"http://www.w3.org/People/Sandro/data#Aaron_Swartz",
//		"http://www.w3.org/People/Sandro/data#Adam_Shostack",
//		"http://www.w3.org/People/Sandro/data#Alex_Newman",
//		"http://www.w3.org/People/Sandro/data#Alicia_Bell",
//		"http://www.w3.org/People/Sandro/data#Allen_Firstenberg",
//		"http://www.w3.org/People/Sandro/data#Amy_Van_der_Hiel",
//		"http://www.w3.org/People/Sandro/data#Antony_Courtney",
//		"http://www.w3.org/People/Sandro/data#Benjamin_Levy",
//		"http://www.w3.org/People/Sandro/data#Beth_Budwig",
//		"http://www.w3.org/People/Sandro/data#Beth_Rosenberg",
//		"http://www.w3.org/People/Sandro/data#Bijan_Parsia",
//		"http://www.w3.org/People/Sandro/data#Bill_Yerazunis",
//		"http://www.w3.org/People/Sandro/data#Blake_Holland",
//		"http://www.w3.org/People/Sandro/data#Bonnie_Denis",
//		"http://www.w3.org/People/Sandro/data#Bryt_Bradley",
//		"http://www.w3.org/People/Sandro/data#Christian_Ratliff",
//		"http://www.w3.org/People/Sandro/data#Dan_Brickley",
//		"http://www.w3.org/People/Sandro/data#Dan_Connolly",
//		"http://www.w3.org/People/Sandro/data#Dan_Nicholas",
//		"http://www.w3.org/People/Sandro/data#Dave_Beckett",
//		"http://www.w3.org/People/Sandro/data#Dave_Belfer-Shevett",
//		"http://www.w3.org/People/Sandro/data#David_Lawrence",
//		"http://www.w3.org/People/Sandro/data#Dawn_Marie_Costorf",
//		"http://www.w3.org/People/Sandro/data#Denis_Parslow",
//		"http://www.w3.org/People/Sandro/data#Deven_Corzine",
//		"http://www.w3.org/People/Sandro/data#Diana_Carroll",
//		"http://www.w3.org/People/Sandro/data#Dwight_Ernest",
//		"http://www.w3.org/People/Sandro/data#Eliz_Lear",
//		"http://www.w3.org/People/Sandro/data#Ellen_Seebacher",
//		"http://www.w3.org/People/Sandro/data#Eric_Miller",
//		"http://www.w3.org/People/Sandro/data#Eric_Prud'hommeaux",
//		"http://www.w3.org/People/Sandro/data#Garance_Drosehn",
//		"http://www.w3.org/People/Sandro/data#George_Walters",
//		"http://www.w3.org/People/Sandro/data#Gerald_Oskoboiny",
//		"http://www.w3.org/People/Sandro/data#Gilly_Rosenthol",
//		"http://www.w3.org/People/Sandro/data#Glen_Daniels",
//		"http://www.w3.org/People/Sandro/data#Gordon_Goldberg",
//		"http://www.w3.org/People/Sandro/data#Greg_Warden",
//		"http://www.w3.org/People/Sandro/data#Hugo_Haas",
//		"http://www.w3.org/People/Sandro/data#Ian_Jacobs",
//		"http://www.w3.org/People/Sandro/data#Inae_Hwang",
//		"http://www.w3.org/People/Sandro/data#Ivan_Herman",
//		"http://www.w3.org/People/Sandro/data#JB_Segal",
//		"http://www.w3.org/People/Sandro/data#Jack_Twilley",
//		"http://www.w3.org/People/Sandro/data#Jacob_Lefton",
//		"http://www.w3.org/People/Sandro/data#James_Elliott",
//		"http://www.w3.org/People/Sandro/data#Janet_Daly",
//		"http://www.w3.org/People/Sandro/data#Jen_Marrs",
//		"http://www.w3.org/People/Sandro/data#Jim_Hendler",
//		"http://www.w3.org/People/Sandro/data#John_Dillon",
//		"http://www.w3.org/People/Sandro/data#John_Rosevear",
//		"http://www.w3.org/People/Sandro/data#Jon_Finke",
//		"http://www.w3.org/People/Sandro/data#Jude_S",
//		"http://www.w3.org/People/Sandro/data#Julia_Rhubin_Bareiss",
//		"http://www.w3.org/People/Sandro/data#Keith_Costorf",
//		"http://www.w3.org/People/Sandro/data#Keith_Rosenblatt",
//		"http://www.w3.org/People/Sandro/data#Lang_Zerner",
//		"http://www.w3.org/People/Sandro/data#Liam_Johnson",
//		"http://www.w3.org/People/Sandro/data#Liam_Quin",
//		"http://www.w3.org/People/Sandro/data#Libby_Miller",
//		"http://www.w3.org/People/Sandro/data#Lynn_Andrea_Stein",
//		"http://www.w3.org/People/Sandro/data#Margaret_Hart",
//		"http://www.w3.org/People/Sandro/data#Mark_Hollinger",
//		"http://www.w3.org/People/Sandro/data#Matt_May",
//		"http://www.w3.org/People/Sandro/data#Matt_Nelson",
//		"http://www.w3.org/People/Sandro/data#Matt_Ringel",
//		"http://www.w3.org/People/Sandro/data#Matt_Rosen",
//		"http://www.w3.org/People/Sandro/data#Matt_W",
//		"http://www.w3.org/People/Sandro/data#Maya_Wallach",
//		"http://www.w3.org/People/Sandro/data#Mitch_Gold",
//		"http://www.w3.org/People/Sandro/data#Nana_Kirk",
//		"http://www.w3.org/People/Sandro/data#Natasha_Hawke",
//		"http://www.w3.org/People/Sandro/data#Nathan_Mehl",
//		"http://www.w3.org/People/Sandro/data#Nicole_Sullivan",
//		"http://www.w3.org/People/Sandro/data#Ofer_Inbar",
//		"http://www.w3.org/People/Sandro/data#Rachel_Mello",
//		"http://www.w3.org/People/Sandro/data#Rachel_Silber",
//		"http://www.w3.org/People/Sandro/data#Rachel_Walters",
//		"http://www.w3.org/People/Sandro/data#Regis_Donovan",
//		"http://www.w3.org/People/Sandro/data#Rehmi_Post",
//		"http://www.w3.org/People/Sandro/data#Roland_McGrath",
//		"http://www.w3.org/People/Sandro/data#Ron_Frederick",
//		"http://www.w3.org/People/Sandro/data#Rosa_Leah",
//		"http://www.w3.org/People/Sandro/data#Rudy_Keiser",
//		"http://www.w3.org/People/Sandro/data#SandroHawke",
//		"http://www.w3.org/People/Sandro/data#Sandro_Hawke",
//		"http://www.w3.org/People/Sandro/data#Scanner_Luce",
//		"http://www.w3.org/People/Sandro/data#Scott_Lefton",
//		"http://www.w3.org/People/Sandro/data#Sean_Palmer",
//		"http://www.w3.org/People/Sandro/data#Shannon_Brophy",
//		"http://www.w3.org/People/Sandro/data#Stefan_Decker",
//		"http://www.w3.org/People/Sandro/data#Stephanie_Doss",
//		"http://www.w3.org/People/Sandro/data#Stephen_Wadlow",
//		"http://www.w3.org/People/Sandro/data#Steven_Pemberton",
//		"http://www.w3.org/People/Sandro/data#Susan_Lesch",
//		"http://www.w3.org/People/Sandro/data#Tamar_Amidon",
//		"http://www.w3.org/People/Sandro/data#Tandy_Ratliff",
//		"http://www.w3.org/People/Sandro/data#Ted_Beatie",
//		"http://www.w3.org/People/Sandro/data#Ted_Thibodeau_Jr",
//		"http://www.w3.org/People/Sandro/data#Tim_Berners-Lee",
//		"http://www.w3.org/People/Sandro/data#Tim_Pierce",
//		"http://www.w3.org/People/djweitzner/foaf#DJW",
//		"http://www.w3.org/People/djweitzner/public/foaf.rdf#djw",
//		"http://www.w3c.es/Personal/Martin/foaf.rdf#Martin",
//		"http://www.w3c.es/Personal/Martin/foaf.rdf#me",
//		"http://www.wchulseiee.net/foaf#elieuw",
//		"http://www.wikier.org/foaf#wikier",
//		"http://www.wikier.org/foaf.rdf#wikier",
//		"http://www.williamviker.net/rdf/foaf.rdf#me",
//		"http://www4.wiwiss.fu-berlin.de/bookmashup/persons/M.+Scott+Marshall",
//		"http://xircles.codehaus.org/users/evenisse/foaf#me",
//		"http://xtrasgu.org/foaf.rdf#xtrasgu",
//		"http://zimmer.aprilfoolsreview.com/antoine#me",
//		"http://www.ifrade.es/#frade"
	};

	static String prefixes = "PREFIX foaf: <http://xmlns.com/foaf/0.1/> " +
							 "PREFIX dc: <http://purl.org/dc/elements/1.1/> " + 
							 "PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#> " +
							 "PREFIX owl: <http://www.w3.org/2002/07/owl#> "+
							 "PREFIX v: <http://www.w3.org/2006/vcard/ns#> ";
	
	//static String baseServer = "http://km.aifb.kit.edu/services/geowrap/";
	static String baseServer = "http://localhost:8888/";
	
	static String findNearbyLIDS = prefixes + "CONSTRUCT { ?point foaf:based_near ?p } " +
											  "FROM <" + baseServer + "findNearby> " +
											  "WHERE { ?point geo:lat ?lat . ?point geo:long ?lng }";
	
	static String alsoNearbyLIDS = prefixes + "CONSTRUCT { ?spatial_entity foaf:based_near ?p } " +
											  "FROM <" + baseServer + "alsoNearby> " +
											  "WHERE { ?spatial_entity foaf:based_near ?point . ?point geo:lat ?lat . ?point geo:long ?lng }";
	
	static String geocodeLIDS = prefixes + "CONSTRUCT { ?entity foaf:based_near ?p . ?p geo:lat ?lat . ?p geo:long ?lng } " +
	  									   "FROM <" + baseServer + "geocode> " +
	  									   "WHERE { ?entity v:adr ?adr . ?adr v:street-address ?street . ?adr v:locality ?town . ?adr v:country-name ?country }";

	public static void main(String args[]) {
		int nKnows[] = new int[people.length];
		int nResults[][] = new int[2][people.length];
		long time[][] = new long[2][people.length];

		try {
			FileWriter out = new FileWriter("results.txt");
			out.write("nKnows timeWith timeWithout nResultsWith nResultsWithout person\n");
			out.close();
		} catch(Exception e) {
			e.printStackTrace();
		}


		int j=0;
		for(String person : people) {
			String nKnowsQ = prefixes + "SELECT ?p WHERE { <" + person + "> foaf:knows ?p }";
			QueryExecutor qKnow = new QueryExecutor(null);
			Collection<Node[]> resultsKnow = qKnow.execQueryWithLIDS(nKnowsQ);
			TreeSet<Node[]> uniqKnow = new TreeSet<Node[]>(NodeComparator.NC);
			uniqKnow.addAll(resultsKnow);
			nKnows[j] = uniqKnow.size();

			for(int i=0;i<2 && nKnows[j] > 0;i++) {
				String queryStr = prefixes + "SELECT ?p ?location WHERE { <" +
				person + "> foaf:knows ?p . ?p foaf:based_near ?point . " +
				" ?point <http://www.geonames.org/ontology#name> ?location }";
				QueryExecutor qe = null;
				if(i == 0) {
					qe = new QueryExecutor(LIDSStrategyBruteForce.getFactory());
				} else {
					qe = new QueryExecutor(null);
				}
				qe.addLIDS(alsoNearbyLIDS);
				qe.addLIDS(geocodeLIDS);
				time[i][j] = System.currentTimeMillis();
				Collection<Node[]> results = qe.execQueryWithLIDS(queryStr);
				time[i][j] = System.currentTimeMillis() - time[i][j];
				nResults[i][j] = results.size();
				System.out.println("For " + person + ":\n");
				for(Node[] res : results) {
					System.out.print(Nodes.toN3(res));
				}
				try {
					FileWriter out = new FileWriter("" + person.substring(8,person.length() - 4).replace('/','.') + i + ".n3");

					for(Node[] nx : qe.dataSet._data) {
						out.write(Nodes.toN3(nx) + "\n");
					}
					out.write("    \n");
					out.close();
				} catch(Exception e) {
					e.printStackTrace();
				}

			}
			try {
				FileWriter out = new FileWriter("results.txt",true);
				out.write(nKnows[j] + " " + time[0][j] + " " + time[1][j] + " " + nResults[0][j] + " " + nResults[1][j] + " " + people[j] + "\n");
				out.close();
			} catch(Exception e) {
				e.printStackTrace();
			}
			j++;
		}

	}


}